db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lunch_app_db}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.username=${DB_USER:root}
db.password=${DB_PASSWORD:Khanh7679@}